# Generated by Django 2.1.5 on 2019-01-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations.User'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
