# Generated by Django 2.1.5 on 2019-01-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20190111_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
