# Generated by Django 2.1.5 on 2019-01-11 13:57

from django.db import migrations
import csv
import os


def add_pokemons(apps, schema_editor):
    Pokemon = apps.get_model('annotations', 'Pokemon')
    with open("./annotations/data/pokemon.csv", "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        fields = next(reader)
        for data in reader:
            data_dict = dict(zip(fields, data))
            pkm = Pokemon(id=data_dict["pokedex_number"], name=data_dict["name"])
            pkm.save()


def remove_pokemons(apps, schema_editor):
    Pokemon = apps.get_model('annotations', 'Pokemon')
    Pokemon.objects.all().delete()

def add_images(apps, schema_editor):
    Image = apps.get_model('annotations', 'Image')
    root_path = "./annotations/data/frames"
    for season_folder in os.listdir(root_path):
        season = int(season_folder[-2:])
        season_path = os.path.join(root_path, season_folder)
        for episode_folder in os.listdir(season_path):
            episode = int(episode_folder[-2:])
            episode_path = os.path.join(season_path,episode_folder)
            for frame_file in os.listdir(episode_path):
                frame = int(frame_file[-13:-4])
                new_frame = Image(season=season, episode=episode, frame=frame)
                new_frame.save()

def remove_images(apps, schema_editor):
    Image = apps.get_model('annotations', 'Image')
    Image.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_remove_image_path'),
    ]

    operations = [
        migrations.RunPython(add_pokemons, remove_pokemons),
        migrations.RunPython(add_images, remove_images)
    ]
