# Generated by Django 2.1.5 on 2019-01-25 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_auto_20190111_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaannotation',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations.Pokemon'),
        ),
    ]
